# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CredifyCore' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for CredifyCore
  
  # Crypto
  pod "CredifyCryptoSwift"
  
  # Utility
  pod 'KeychainAccess'
  
  # Rx
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'

end
