# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CredifyKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CredifyKit
  
  # Crypto
  pod "CredifyCryptoSwift"
  
  # Utility
  pod 'KeychainAccess'
  
  # Rx
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  
  #UI
  pod 'lottie-ios'
  pod 'Kingfisher'

  target 'CredifyKitTests' do
    # Pods for testing
  end

end

target 'ExampleApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Crypto
  pod "CredifyCryptoSwift"
  
  # Utility
  pod 'KeychainAccess'
  
  # Rx
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  
  #UI
  pod 'lottie-ios'
  pod 'Kingfisher'
  
  #Network
  pod 'Alamofire', '~> 5.2'

  # Pods for ExampleApp

end
